---
title: "NJ interactive map"
author: "Lei Song"
date: "2026-03-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=F, results='hide', warning=F, message=F}
# install.packages('tigris')
# install.packages("USAboundaries")
# devtools::install_github("ropensci/USAboundariesData")
library(sf)
library(dplyr)
library(tigris)
library(USAboundaries)
library(stringr)
library(leaflet)

library(sf)
library(dplyr)
library(tigris)
library(USAboundaries)
library(stringr)
library(leaflet)
sf_use_s2(FALSE)

# Get the boundary of piscataway only
piscataway_bry <- county_subdivisions(
  state = 'NJ', county = 'Middlesex') %>% 
  filter(NAME == 'Piscataway')

# Get the census tracks for Middlesex
mids_tracts <- tracts(state = 'NJ', county = 'Middlesex') %>% 
  mutate(NAME_GROUP = str_extract(NAME, "[0-9]+"))

# Get all counties in NJ
nj_counties <- counties(state = 'NJ')

# Get all cities in NJ
nj_cities <- us_cities(states = 'NJ')

# Get the coordinates of the centroid of piscataway_bry
## Finish the line
ctr <- st_coordinates(st_centroid(piscataway_bry))

p <- leaflet() %>%
  # Set default view
  setView(ctr[1], ctr[2], zoom = 9) %>%
  # Base layer groups
  addTiles() %>% 
  # Overlay layer groups
  addPolygons(data = nj_counties, 
              fillColor = 'pink',
              color = 'red', weight = 2,
              fillOpacity = 0.4,
              group = "NJ counties") %>%
  addPolygons(data = mids_tracts, 
              fillColor = ~colorFactor("Set3", NAME_GROUP)(NAME_GROUP),
              color = 'black', weight = 2,
              opacity = 1, fillOpacity = 1,
              group = "Middlesex tracts") %>% 
  addCircles(data = nj_cities, weight = 1,
    radius = ~sqrt(population) * 15, popup = ~city,
    group = "Population") %>% 
  addPolygons(data = piscataway_bry,
              color = 'yellow', weight = 3,
              opacity = 1, fillOpacity = 0,
              group = "Middlesex") %>% 
  addLayersControl(
    baseGroups = c("OpenStreetMap"),
    overlayGroups = c("NJ counties", "Middlesex tracts", 
                      "Population", "Middlesex"),
    options = layersControlOptions(collapsed = FALSE))
```

```{r, echo=F, fig.align='center', fig.height=6, fig.width=10}
p
```
